FROM public.ecr.aws/docker/library/golang:1.19 as build-image
WORKDIR /src
COPY go.mod go.sum ./
COPY lambda/get-live-fixtures.go ./main.go
COPY lambda/model ./model
COPY tmp/get-live-fixtures-lambda-handler ./
FROM public.ecr.aws/lambda/provided:al2
COPY --from=build-image /src/get-live-fixtures-lambda-handler .
ENTRYPOINT ./get-live-fixtures-lambda-handler
