AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aceface
  
  Sample SAM Template for aceface

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Parameters:
  TABLENAME:
    Type: String
    Description: The DynamoDB table for storing Fixture information.
    Default: 'aceface-fixture'

  REGIONNAME:
    Type: String
    Description: Default region for deployment.
    Default: 'eu-west-2'

  AWSENVNAME:
    Type: String
    Description: AWS Environment where code is being executed (AWS_SAM_LOCAL or AWS).
    Default: 'AWS_SAM_LOCAL'

  DEVENVNAME:
    Type: String
    Description: Developer environment where code is being executed (OSX, Windows, or Linux).
    Default: 'OSX'

Resources:
  GetLiveFixturesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /fixtures
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          TABLE: !Ref TABLENAME
          REGION: !Ref REGIONNAME
          AWSENV: !Ref AWSENVNAME
          DEVENV: !Ref DEVENVNAME
    Metadata:
      DockerTag: provided.al2-v1
      DockerContext: ./
      Dockerfile: Dockerfile.get-live-fixtures

  FixturesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TABLENAME
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: N
        - AttributeName: SK
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetLiveFixturesAPI:
    Description: "API Gateway endpoint URL for Prod environment for getLiveFixtures Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fixtures/"
  GetLiveFixturesFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt GetLiveFixturesFunction.Arn
  GetLiveFixturesFunctionIamRole:
    Description: "Implicit IAM Role created for getLiveFixtures function"
    Value: !GetAtt GetLiveFixturesFunctionRole.Arn


